### ISSUE TITLE
helper not found

### ISSUE THREAD

**Issue by PhilTrue** [icicletech/ember-cli-full-calendar#1]
I followed the instructions in the readme, and I get this error:

Uncaught Error: Assertion Failed: A helper named 'full-calendar' could not be found

Ember 1.13.3

when I ran `ember g full-calendar`, the only change in my project was a change to bower.json, adding moment.js

when I ran `npm install --save-dev ember-cli-full-calendar`, the only change I noticed was to package.json, adding the ember-cli add-on.

Seems like maybe ember g should have done more?

**Comment by shrivaraks** [comment]
@PhilTrue Could you post the version of `ember-cli` you are using?

**Comment by PhilTrue** [comment]
ember-cli version 1.13.1

**Comment by shrivaraks** [comment]
Unable to reproduce the issue with 1.13.8, try upgrading the version. Closing this for now. Feel free to reopen if the issue persists.
