### ISSUE TITLE
ember-cli-full-calendar is not a properly formatted package

### ISSUE THREAD

**Issue by celicoo** [icicletech/ember-cli-full-calendar#14]
I'm trying to install the package, but the following error happens:

The package `ember-cli-full-calendar` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/Trabalho/PubCrawl/Admin/node_modules/ember-cli-full-calendar`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ember-cli-full-calendar` addon could not be found at `/Users/Trabalho/PubCrawl/Admin/node_modules/ember-cli-full-calendar`.

**Comment by jamesdixon** [comment]
I'm also getting this error. However, it did not occur until I upgraded from Ember CLI 1.13.8 to 1.13.12.

**Comment by jamesdixon** [comment]
@shrivaraks I did some more investigating and it appears that there is an issue with the `0.0.15` release on NPM. When installing, indeed there is no `index.js` in the package. However, if I downgrade to `0.0.14`, there are no errors and there is an `index.js` file in the package.

**Comment by celicoo** [comment]
hei @jamesdixon, i'm going to try downgrade too.

Thank you!

**Comment by jamesdixon** [comment]
@celicoo no problem! Hope it worked!
