### ISSUE TITLE
Support for Fullcalendar Scheduler

### ISSUE THREAD

**Issue by jamesdixon** [icicletech/ember-cli-full-calendar#3]
Hi,

Great work on this component thus far! Just wanted to see if you had any plans to support [Fullcalendar Scheduler](http://fullcalendar.io/scheduler/), which is a new add-on that was recently released.

Thanks,
James

**Comment by shrivaraks** [comment]
Hi, thanks for the suggestion. We could maybe add a separate generator which also includes the scheduler, `full-calendar-scheduler`, this way I think if only the calendar is required, `full-calendar` can be used and for the scheduler component, `full-calendar-scheduler` can be used. Thoughts?

Thanks!

**Comment by jamesdixon** [comment]
Hi @shrivaraks. Yes, I believe that makes complete sense given that the Fullcalendar Scheduler is a separate install. Anything I can do to assit?

**Comment by shrivaraks** [comment]
I'm adding a new generator. I'll push it here in one or two days.

**Comment by shrivaraks** [comment]
@jamesdixon This got delayed and I don't think I'll be working on this. Open to a PR.
