### ISSUE TITLE
Not all properties working

### ISSUE THREAD

**Issue by jamesdixon** [icicletech/ember-cli-full-calendar#4]
Hi,

I attempted to set `weekends` to `false` and unfortunately, it didn't work. When digging into the code, it looks like not all properties are hooked up. I'm sure you are aware of this, but just wanted to mention it. I need to get working on things, so I may hook things up as I go; would you accept a PR?

Thanks!
James

**Comment by shrivaraks** [comment]
Hi, yeah a few of the properties are not hooked up yet. Any help is greatly appreciated! Will gladly accept a PR.

Thanks!

**Comment by jamesdixon** [comment]
Awesome! Thanks!
