### ISSUE TITLE
Can you update npm version of your addon ?

### ISSUE THREAD

**Issue by jakkor** [icicletech/ember-cli-full-calendar#44]
I need now to use github code instead of downloading this with npm to get the latest changes.

Btw I need now almost all of the full calendar options so I will probably try to add everything to this addon in near future. I hope that's not a problem.

**Comment by shrivaraks** [comment]
Hey, that's definitely _not_ a problem. I'll update the version for now. I'll make the suitable changes in `travis.yml` so we start auto-publishing.

@wicliff Could you please add @jakkor as a collaborator here. Thanks.

**Comment by shrivaraks** [comment]
Please use `0.1.1`. The package will now start auto-publishing for every version change.
