### ISSUE TITLE
Custom Navigation is not working

### ISSUE THREAD

**Issue by jigneshchudasama05** [icicletech/ember-cli-full-calendar#50]
````
import Ember from 'ember';

export default Ember.Controller.extend({
	queryParams: ['from', 'to'],
  	events: null,
  	accessToFullCalendar: null,
  
	eventRender: function(event, element) {
        element.children().children().attr("data-content", event.projectName + ' - ' + event.userName + ' - ' + event.hours + 'hr(s)');
		element.children().children().popup({
			on: 'hover'
		});
    },
    
    actions: {
	    prev: function() {
	    	this.get('accessToFullCalendar').send('prev');
	    }
  	}
});

````

````
<div class="max-width-1170">
	<button {{action 'prev'}}>Prev</button>
	{{full-calendar
	events=events
	allDaySlot=false
	eventLimit=3
	eventRender=eventRender
	register-as='accessToFullCalendar'
	nowIndicator=true}}
</div>
````

It's showing me 'Uncaught TypeError: Cannot read property 'send' of null' error

**Comment by shrivara** [comment]
Try removing the quotes in `register-as`.

**Comment by jigneshchudasama05** [comment]
I tried that also but no luck

**Comment by shrivara** [comment]
Which version of the module are you using?

**Comment by jigneshchudasama05** [comment]
The latest one i.e 0.1.4

**Comment by shrivara** [comment]
I'll take a look.

**Comment by shrivara** [comment]
Also, what version of ember are you on?

**Comment by jigneshchudasama05** [comment]
Thanks! Ember version is  1.13.7

**Comment by shrivara** [comment]
I took a stab at this with the [dummy](https://github.com/icicletech/ember-cli-full-calendar/tree/master/tests/dummy/app) app with 1.13.7. It worked as expected.
Could you take a look at that and see if you're missing something?

**Comment by jigneshchudasama05** [comment]
I already tried that but same result :(

**Comment by shrivara** [comment]
Here is a [branch](https://github.com/icicletech/ember-cli-full-calendar/compare/master...issue_50) with your changes, I'm still not able to repro the failure.

**Comment by shrivara** [comment]
Closing this now as I'm not able to debug this further without repro steps. Do reopen if you have a small sample. Thanks.

**Comment by jigneshchudasama05** [comment]
Thanks! will look into and will let you know!
