### ISSUE TITLE
How to get current selected month on custom button click

### ISSUE THREAD

**Issue by jigneshchudasama05** [icicletech/ember-cli-full-calendar#51]
How to get previous/next month on click of custom previous/next button but before prev/next action called?

````
Controller: 
actions: {
    prev: function() {
    	this.get('accessToFullCalendar').send('prev');
    }
}
````

````
Template: 
<div>
	
  <button {{action 'prev'}}>Prev</button>
	<button {{action 'next'}}>Next</button>

	{{full-calendar
    events=events
    allDaySlot=false
    eventLimit=3
    eventRender=eventRender
    register-as='accessToFullCalendar'
    nowIndicator=true}}
</div>
````

**Comment by jamesdixon** [comment]
@jigneshchudasama05 I ran into something similar and hooked into the `viewRender` method. It passes in a `view` object, which contains that type of information.

**Comment by jigneshchudasama05** [comment]
Thanks @jamesdixon will try this :-)

@shrivara Please let me know your thoughts on this? :-)
