### ISSUE TITLE
Conflict w/ ember-moment

### ISSUE THREAD

**Issue by jamesdixon** [icicletech/ember-cli-full-calendar#6]
Hi,

I'm using [ember-moment](https://github.com/stefanpenner/ember-moment) in my project, with moment-timezone enabled. Unfortunately, with your addon installed, it breaks moment-timezone. See my [issue on ember-moment here](https://github.com/stefanpenner/ember-moment/issues/93). I'm going to poke around and see if I can figure it out, but was hoping you might be able to lend some insight.

Thanks!

**Comment by jamesdixon** [comment]
So commenting out [line 10](https://github.com/icicletech/ember-cli-full-calendar/blob/master/index.js#L10), which imports moment, solves the issue. I would think that `app.import` would prevent a duplicate library from being added, but maybe there is a better way to check this.

**Comment by jasonmit** [comment]
To make all of these libs work (including ember-pikaday) I suggest they leverage ember-cli-moment-shim that handles the actual importing of moment and the timezone + locales in specific ordering.
